import Foundation
import SwiftProtobuf
import SwiftProtobufPluginLibrary

@main
struct TTRPCGenerator: CodeGenerator {
    var supportedFeatures: [Google_Protobuf_Compiler_CodeGeneratorResponse.Feature] = [.proto3Optional]

    var version: String? { "0.1.0" }

    func generate(
        files: [FileDescriptor],
        parameter: any CodeGeneratorParameter,
        protoCompilerContext: any ProtoCompilerContext,
        generatorOutputs: any GeneratorOutputs
    ) throws {
        for fileDescriptor in files {
            guard !fileDescriptor.services.isEmpty else { continue }

            var printer = CodePrinter()
            generateFileHeader(&printer, fileDescriptor: fileDescriptor)
            generateImports(&printer)

            for service in fileDescriptor.services {
                generateServerProtocol(&printer, service: service)
                printer.println()
                generateServiceDescriptorExtension(&printer, service: service)
                printer.println()
                generateClient(&printer, service: service)
                printer.println()
            }

            let fileName = fileDescriptor.name.replacingOccurrences(of: ".proto", with: ".ttrpc.swift")
            try generatorOutputs.add(fileName: fileName, contents: printer.content)
        }
    }

    // MARK: - File Header

    private func generateFileHeader(_ p: inout CodePrinter, fileDescriptor: FileDescriptor) {
        p.println("// DO NOT EDIT.")
        p.println("// swift-format-ignore-file")
        p.println("// swiftlint:disable all")
        p.println("//")
        p.println("// Generated by protoc-gen-swift-ttrpc. DO NOT EDIT!")
        p.println("// Source: \(fileDescriptor.name)")
        p.println()
    }

    // MARK: - Imports

    private func generateImports(_ p: inout CodePrinter) {
        p.println("import Foundation")
        p.println("import SwiftProtobuf")
        p.println("import TTRPCCore")
        p.println("import TTRPCClient")
        p.println("import TTRPCServer")
        p.println("import TTRPCProtobuf")
        p.println()
    }

    // MARK: - Server Protocol

    private func generateServerProtocol(_ p: inout CodePrinter, service: ServiceDescriptor) {
        let protoName = protoServiceName(service)
        let protocolName = "\(protoName)_TTRPCService"

        p.println("/// Server protocol for the `\(service.fullName)` service.")
        p.println("public protocol \(protocolName): TTRPCServiceRegistration {")
        p.indent()

        for method in service.methods {
            generateServerMethodSignature(&p, method: method)
        }

        p.outdent()
        p.println("}")
    }

    private func generateServerMethodSignature(_ p: inout CodePrinter, method: MethodDescriptor) {
        let inputType = swiftTypeName(for: method.inputType)
        let outputType = swiftTypeName(for: method.outputType)
        let methodName = lowerCamelCase(method.name)

        if !method.clientStreaming && !method.serverStreaming {
            p.println("func \(methodName)(request: \(inputType), context: TTRPCHandlerContext) async throws -> \(outputType)")
        } else if method.clientStreaming && !method.serverStreaming {
            p.println("func \(methodName)(stream: TTRPCServerStreamInterface, context: TTRPCHandlerContext) async throws -> \(outputType)")
        } else if !method.clientStreaming && method.serverStreaming {
            p.println("func \(methodName)(request: \(inputType), stream: TTRPCServerStreamInterface, context: TTRPCHandlerContext) async throws")
        } else {
            p.println("func \(methodName)(stream: TTRPCServerStreamInterface, context: TTRPCHandlerContext) async throws")
        }
    }

    // MARK: - Service Descriptor Extension

    private func generateServiceDescriptorExtension(_ p: inout CodePrinter, service: ServiceDescriptor) {
        let protoName = protoServiceName(service)
        let protocolName = "\(protoName)_TTRPCService"

        p.println("extension \(protocolName) {")
        p.indent()
        p.println("public var serviceDescriptor: TTRPCServiceDescriptor {")
        p.indent()

        let unaryMethods = service.methods.filter { !$0.clientStreaming && !$0.serverStreaming }
        let streamMethods = service.methods.filter { $0.clientStreaming || $0.serverStreaming }

        p.println("TTRPCServiceDescriptor(")
        p.indent()
        p.println("name: \"\(service.fullName)\",")

        if unaryMethods.isEmpty {
            p.println("methods: [:]\(streamMethods.isEmpty ? "" : ",")")
        } else {
            p.println("methods: [")
            p.indent()
            for (i, method) in unaryMethods.enumerated() {
                generateUnaryMethodDescriptor(&p, method: method, isLast: i == unaryMethods.count - 1)
            }
            p.outdent()
            p.println("]\(streamMethods.isEmpty ? "" : ",")")
        }

        if streamMethods.isEmpty {
            p.println("streams: [:]")
        } else {
            p.println("streams: [")
            p.indent()
            for (i, method) in streamMethods.enumerated() {
                generateStreamMethodDescriptor(&p, method: method, isLast: i == streamMethods.count - 1)
            }
            p.outdent()
            p.println("]")
        }

        p.outdent()
        p.println(")")
        p.outdent()
        p.println("}")
        p.outdent()
        p.println("}")
    }

    private func generateUnaryMethodDescriptor(_ p: inout CodePrinter, method: MethodDescriptor, isLast: Bool) {
        let inputType = swiftTypeName(for: method.inputType)
        let methodName = lowerCamelCase(method.name)
        let comma = isLast ? "" : ","

        p.println("\"\(method.name)\": TTRPCMethodDescriptor(")
        p.indent()
        p.println("name: \"\(method.name)\",")
        p.println("handler: { context, data in")
        p.indent()
        p.println("let codec = TTRPCProtobufCodec()")
        p.println("let request: \(inputType) = try codec.unmarshal(data)")
        p.println("let response = try await self.\(methodName)(request: request, context: context)")
        p.println("return try codec.marshal(response)")
        p.outdent()
        p.println("}")
        p.outdent()
        p.println(")\(comma)")
    }

    private func generateStreamMethodDescriptor(_ p: inout CodePrinter, method: MethodDescriptor, isLast: Bool) {
        let inputType = swiftTypeName(for: method.inputType)
        let methodName = lowerCamelCase(method.name)
        let comma = isLast ? "" : ","

        p.println("\"\(method.name)\": TTRPCStreamDescriptor(")
        p.indent()
        p.println("name: \"\(method.name)\",")
        p.println("clientStreaming: \(method.clientStreaming),")
        p.println("serverStreaming: \(method.serverStreaming),")
        p.println("handler: { context, stream in")
        p.indent()

        if !method.clientStreaming && method.serverStreaming {
            p.println("let codec = TTRPCProtobufCodec()")
            p.println("let data = try await stream.receiveData()")
            p.println("let request: \(inputType) = try codec.unmarshal(data)")
            p.println("try await self.\(methodName)(request: request, stream: stream, context: context)")
        } else if method.clientStreaming && !method.serverStreaming {
            p.println("let codec = TTRPCProtobufCodec()")
            p.println("let response = try await self.\(methodName)(stream: stream, context: context)")
            p.println("let data = try codec.marshal(response)")
            p.println("try await stream.sendData(data)")
            p.println("try await stream.closeSend()")
        } else {
            p.println("try await self.\(methodName)(stream: stream, context: context)")
        }

        p.outdent()
        p.println("}")
        p.outdent()
        p.println(")\(comma)")
    }

    // MARK: - Client

    private func generateClient(_ p: inout CodePrinter, service: ServiceDescriptor) {
        let protoName = protoServiceName(service)
        let clientName = "\(protoName)_TTRPCClient"

        p.println("/// Client for the `\(service.fullName)` service.")
        p.println("public struct \(clientName): Sendable {")
        p.indent()
        p.println("private let client: TTRPCClient")
        p.println()
        p.println("public init(client: TTRPCClient) {")
        p.indent()
        p.println("self.client = client")
        p.outdent()
        p.println("}")

        for method in service.methods {
            p.println()
            generateClientMethod(&p, method: method, service: service)
        }

        p.outdent()
        p.println("}")
    }

    private func generateClientMethod(_ p: inout CodePrinter, method: MethodDescriptor, service: ServiceDescriptor) {
        let inputType = swiftTypeName(for: method.inputType)
        let outputType = swiftTypeName(for: method.outputType)
        let methodName = lowerCamelCase(method.name)

        if !method.clientStreaming && !method.serverStreaming {
            p.println("public func \(methodName)(_ request: \(inputType), timeout: Duration? = nil, metadata: TTRPCMetadata? = nil) async throws -> \(outputType) {")
            p.indent()
            p.println("try await client.call(")
            p.indent()
            p.println("service: \"\(service.fullName)\",")
            p.println("method: \"\(method.name)\",")
            p.println("request: request,")
            p.println("responseType: \(outputType).self,")
            p.println("timeout: timeout,")
            p.println("metadata: metadata")
            p.outdent()
            p.println(")")
            p.outdent()
            p.println("}")
        } else if !method.clientStreaming && method.serverStreaming {
            p.println("public func \(methodName)(_ request: \(inputType), timeout: Duration? = nil, metadata: TTRPCMetadata? = nil) async throws -> TTRPCClientStream<\(inputType), \(outputType)> {")
            p.indent()
            p.println("try await client.makeStream(")
            p.indent()
            p.println("service: \"\(service.fullName)\",")
            p.println("method: \"\(method.name)\",")
            p.println("request: request,")
            p.println("responseType: \(outputType).self,")
            p.println("clientStreaming: false,")
            p.println("serverStreaming: true,")
            p.println("timeout: timeout,")
            p.println("metadata: metadata")
            p.outdent()
            p.println(")")
            p.outdent()
            p.println("}")
        } else if method.clientStreaming && !method.serverStreaming {
            p.println("public func \(methodName)(timeout: Duration? = nil, metadata: TTRPCMetadata? = nil) async throws -> TTRPCClientStream<\(inputType), \(outputType)> {")
            p.indent()
            p.println("try await client.makeStream(")
            p.indent()
            p.println("service: \"\(service.fullName)\",")
            p.println("method: \"\(method.name)\",")
            p.println("request: \(inputType)(),")
            p.println("responseType: \(outputType).self,")
            p.println("clientStreaming: true,")
            p.println("serverStreaming: false,")
            p.println("timeout: timeout,")
            p.println("metadata: metadata")
            p.outdent()
            p.println(")")
            p.outdent()
            p.println("}")
        } else {
            p.println("public func \(methodName)(timeout: Duration? = nil, metadata: TTRPCMetadata? = nil) async throws -> TTRPCClientStream<\(inputType), \(outputType)> {")
            p.indent()
            p.println("try await client.makeStream(")
            p.indent()
            p.println("service: \"\(service.fullName)\",")
            p.println("method: \"\(method.name)\",")
            p.println("request: \(inputType)(),")
            p.println("responseType: \(outputType).self,")
            p.println("clientStreaming: true,")
            p.println("serverStreaming: true,")
            p.println("timeout: timeout,")
            p.println("metadata: metadata")
            p.outdent()
            p.println(")")
            p.outdent()
            p.println("}")
        }
    }

    // MARK: - Naming Helpers

    private func protoServiceName(_ service: ServiceDescriptor) -> String {
        let parts = service.fullName.split(separator: ".")
        return parts.map { part in
            var s = String(part)
            if let first = s.first {
                s = String(first).uppercased() + s.dropFirst()
            }
            return s
        }.joined(separator: "_")
    }

    private func swiftTypeName(for descriptor: Descriptor) -> String {
        let parts = descriptor.fullName.split(separator: ".")
        return parts.map { part in
            var s = String(part)
            if let first = s.first {
                s = String(first).uppercased() + s.dropFirst()
            }
            return s
        }.joined(separator: "_")
    }

    private func lowerCamelCase(_ name: String) -> String {
        guard let first = name.first else { return name }
        return String(first).lowercased() + name.dropFirst()
    }
}

// MARK: - Simple Code Printer

struct CodePrinter {
    private var buffer = ""
    private var indentLevel = 0
    private let indentString = "    "

    var content: String { buffer }

    mutating func println(_ text: String = "") {
        if text.isEmpty {
            buffer += "\n"
        } else {
            buffer += String(repeating: indentString, count: indentLevel) + text + "\n"
        }
    }

    mutating func indent() {
        indentLevel += 1
    }

    mutating func outdent() {
        indentLevel = max(0, indentLevel - 1)
    }
}
